src/j3d/zww_scenes.ts
Fixing Zelda's eyes materials.
=> Fixing Zelda eyes

src/Camera.ts
Adding ability to use arrow keys to control the camera. Also used page
up and page down to move up and down, because that kind of made sense. I could go either way with the page up and page down buttons, but it seemed like a logical addition to me.
Based on feedback from here:
https://twitter.com/magnetic_tape/status/1100463350176247808
=> Adding ability to use arrow keys to control the camera

src/rres/zss_scenes.ts
Include Skyloft scene names, remove from untagged, add contributor
=> Include Skyloft scene names

src/oot3d/oot3d_scenes.ts
All objects in Lon Lon Ranch Stables added
=> Added objects to Oot3d Stable Scene

src/oot3d/oot3d_scenes.ts
=> New objects for Oot3d

src/oot3d/oot3d_scenes.ts
includes proper chest models and scales, hookshot targets, torches, and a few other objects.
=> More objects in Oot3d Scenes, Fixed Chests

src/oot3d/oot3d_scenes.ts
Guards, a couple things in zelda's garden, half of shopkeepers, some things in jabu jabu's belly and a few other objects.
=> More Objects in Oot3d

src/kh/bin.ts, src/kh/bin_tex.ts, src/kh/program.glsl, src/kh/render.ts, src/kh/scenes.ts, src/main.ts
Parser and renderer for maps from Kingdom Hearts (PS2). Each scene loads a .bin and .img file pair from data/kh.
=> Add support for Kingdom Hearts

src/sm64ds/scenes.ts
Includes sorting by ID, objects not used in scenes have been skipped.
http://kuribo64.net/sm64ds/objectdb.php
=> (Pat) [SM64DS] Completed object database(!)

src/Pilotwings64/Scenes.ts
I'm happy to leave in the "all contour" mode. It seems like the ones that aren't in levels are portions of the big USA map, could be for testing.
=> Pilotwings 64: Group terrain by level.

src/Pilotwings64/Scenes.ts
Doesn't work right now, but the model parsing is correct at least.
=> Pilotwings 64: Parse and render model files.

src/Pilotwings64/Scenes.ts
Still some unresolved questions w/r/t model parts, but getting there.
=> Pilotwings 64: Render static models in the right place.

src/Pilotwings64/Scenes.ts
Also change uses of "blend" to "combine" to be more accurate.
I had to do some weird things to smuggle an integer array into the shader: I got an error about precision mismatch between the vertex and fragment shaders if i used a uvec directly and got weird data integrity errors if i moved the uniform buffer definition to just the fragment shader. I'm hoping you can show me the real way.
By "data integrity" errors, I mean the shader output would change dramatically if I resized the window, not really sure how that's possible.
=> Pilotwings 64: Add crazy combine shader.

src/Pilotwings64/Scenes.ts
Also render each model as a unit, handling relative positions.
I'm not sure what the deal is with Mount Rushmore. Perhaps it had an animation that was taken out? The animation parameters are all taken from the code, the only "toy" data in the file system is the coordinates of the toys, used for lookup.
=> Pilotwings 64: Animate toys.

src/Pilotwings64/Scenes.ts
The current data doesn't use very many modes, so the mapping
to Gfx modes is mostly straightforward so far.
The render passes are just an approximation for now.
It's probably time to start splitting this file up. Some of the enums could be moved to the f3dex file, though the geo flags definitely changed. There are definitely still some mismatches between my intuition and how things are actually showing up (decals still seem to be z-fighting, etc.).
=> Pilotwings 64: Implement basic blending modes.

src/Pilotwings64/Scenes.ts
Adding more will be rather painstaking, hopefully this framework
is robust enough for the other movement types.
I'm doing some maybe-iffy things with optional/undefined here just because I don't know the language well enough to be aware of alternatives.
=> Pilotwings64: Start on Dobj support: boats!

src/Pilotwings64/Scenes.ts
Use two derivatives of the spline (the game uses one) to make
the logic less dependent on a monotonic timer.
Only the plane SPTH objects are parsed now - the others have mismatched
numbers of keyframes, so might be interpreted differently.
=> Pilotwings64: Add airplanes and some SPTH parsing.

src/Pilotwings64/Scenes.ts
Based mostly on roto's work. Rings still have some weird things
going on (and seem to all have the clock hands). Scaling on the
thermals was just a guess.
The messy landing pad logic could might better be done by just allowing
the two landing pads to draw at the same time, knowing the active one
will be drawn second.
=> Pilotwings64: Add task objects.

src/Pilotwings64/Scenes.ts
- Implement texture palette, refactoring how DataHolder is used
- Load skybox and ocean plane from UVEN
- Also add back ring angles and fix landing pad bug, whoops
=> Pilotwings64: Allow weather/time selection.

src/GrandTheftAuto3/item.ts, src/GrandTheftAuto3/program.glsl, src/GrandTheftAuto3/render.ts, src/GrandTheftAuto3/scenes.ts, src/GrandTheftAuto3/time.ts
This renders ambient lighting according to simulated time of day and selected weather scenario.
=> GTA3 lighting and improved performance

package.json, src/GrandTheftAuto3/item.ts, src/GrandTheftAuto3/program.glsl, src/GrandTheftAuto3/render.ts, src/GrandTheftAuto3/scenes.ts, src/GrandTheftAuto3/time.ts, src/GrandTheftAuto3/water.ts, yarn.lock
The loading time of the complete map should also be improved as it doesn't load as many tiny files now.
=> GrandTheftAuto3: water and sky

src/Pilotwings64/Scenes.ts
Each snowflake is a quad, smuggling in a corner identifier
for proper billboarding.
=> Pilotwings64: Let it snow!

src/bk/tools/extractor.ts
Also load the setup files. Three levels differ from the hardcoded values:
- Nabnut's Attic - Fall is identical to Attic 2 instead of Attic - Winter
- Grunty's Lair Floor 5 has a skylight effect over the urn
- Grunty's Lair Floor 8 has another skylight-ish effect
=> bk: Parse file mappings from game data.

src/GrandTheftAuto3/render.ts, src/GrandTheftAuto3/scenes.ts
This seems to fix all the transparency sorting issues I'd noticed in Vice City.
=> GrandTheftAuto: fix transparency sorting

src/GrandTheftAuto3/render.ts
Fixes that missing lot and a couple of regressions.
=> GTA: minor fixes

src/metroid_prime/mrea.ts, src/metroid_prime/render.ts
I only implemented type 0 which just uses the raw matrix it generates, I didn't implement the other types yet, because they seem to be unused in the data
=> mp3: Add UV mode 8 support

src/j3d/WindWaker/zww_scenes.ts
They used to show as green rupees.
=> zww: Hearts use correct model

src/j3d/WindWaker/zww_scenes.ts
Multiple small updates. See commits.
=> zww: Forsaken Fortress

src/j3d/mkdd_scenes.ts
Moves Double Dash off the basic J3D renderer and onto its own
=> mkdd: Mirror Courses render hack

src/j3d/WindWaker/zww_scenes.ts
_This one's been sitting around in my fork for a while. What do you think?_
ToD starts at DAY by default, with a 60 second day cycle (10 seconds per phase).
=> Wind Waker: A bit more control over time of day handling

src/InputManager.ts
This PR scales touch events relative to the canvas size. This ensures that scrolling and panning function at consistent speeds on different screen resolutions.
=> Scale touch-handling to be consistent w.r.t. screen sizes

src/SpongeBobBFBB/assets.ts, src/SpongeBobBFBB/program.glsl, src/SpongeBobBFBB/render.ts, src/SpongeBobBFBB/scenes.ts
PIPT settings are supported more accurately, allowing for per-object alpha testing and fog/light filtering. Basic gouraud shading is implemented, looks decent in some levels, bad in others. I added a render hacks panel for toggling lighting on/off.
=> BFBB: Improved PIPT and lighting support

src/SpongeBobBFBB/assets.ts, src/SpongeBobBFBB/enums.ts, src/SpongeBobBFBB/program.glsl, src/SpongeBobBFBB/render.ts, src/SpongeBobBFBB/scenes.ts, src/SpongeBobBFBB/util.ts
This adds support for pickups (with animations 😮), destructible objects, and fixes a few depth testing issues.
=> BFBB: Add pickups, destructible objects, and fixed some depth testing issues

src/oot3d/mm3d_scenes.ts
=> Added Beamos to mm3d scene

src/zelview/f3dzex.ts
Replace console.exception with console.error.
=> zelview: Fix loading Kakariko Village in Chrome

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/resource.ts, src/StarFoxAdventures/scenes.ts, src/StarFoxAdventures/textures.ts
This PR implements "ancient" maps from the demo-- fossilized remains of the game that could have been Dinosaur Planet for the Nintendo 64. These maps are categorized under Star Fox Adventures.
Although these maps were deleted from the final game, their landscape geometry remains in buried in the demo's files. I recreated some of these maps by hand. Since the original textures were missing, false textures are used to make the geometry discernible.
=> SFA: Implement ancient maps from the demo

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/resource.ts, src/StarFoxAdventures/scenes.ts, src/StarFoxAdventures/textures.ts, src/StarFoxAdventures/world.ts
This PR implements mip-maps in Star Fox Adventures. Maps look smoother from a distance. Also included are various cleanups and a preliminary implementation of game objects (currently disabled).
=> SFA: Implement mip-maps

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/envfx.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/scenes.ts, src/StarFoxAdventures/textures.ts, src/StarFoxAdventures/world.ts
This PR makes certain objects and textures, such as the dirt paths in ThornTail Hollow, look more like their appearance in the game.
Also included is some prototype code related to environment effects and object rendering. This is currently disabled.
=> SFA: Improve faithfulness of materials to the game

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/shaders.ts
This PR improves the look of water, and implements the reflective floors in Krazoa Palace (which looked rather bizarre in the game, too).
=> Improve water and reflective surfaces in Star Fox Adventures

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/fur.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/resource.ts, src/StarFoxAdventures/shaders.ts, src/StarFoxAdventures/textures.ts, src/StarFoxAdventures/util.ts, src/StarFoxAdventures/world.ts
This PR implements the grass in ThornTail Hollow. Grass will only appear within a short distance of the camera. It is not fully game-accurate yet, this is a work-in-progress but it looks pretty good so far.
=> SFA: Implement grass in ThornTail Hollow and other maps

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/shaders.ts, src/StarFoxAdventures/util.ts, src/StarFoxAdventures/world.ts
This PR implements caustic reflections (used mostly in Cape Claw), and improves the appearance of water and lava.
Thanks again, Jasper, for helping with the water effects!
=> SFA: Implement caustic reflections and improve other environment effects

src/StarFoxAdventures/animation.ts, src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/scenes.ts, src/StarFoxAdventures/shaders.ts, src/StarFoxAdventures/util.ts, src/StarFoxAdventures/world.ts
This PR implements animated environmental effects. Lakes and rivers are animated but waterfalls are only animated in full scenes.
Three more full scenes are available.
=> SFA: Implement animated water and other environment effects; add more full scenes

src/StarFoxAdventures/animation.ts
=> SFA: Fix filename capitalization

src/StarFoxAdventures/animation.ts, src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/modelexhibit.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/scenes.ts, src/StarFoxAdventures/world.ts, src/gx/gx_displaylist.ts
Fine skinning can still be disabled with `main.scene.enableFineAnims(false)` .
=> SFA: Improve fine skinning performance and enable by default

src/StarFoxAdventures/animation.ts, src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/envfx.ts, src/StarFoxAdventures/materials.ts, src/StarFoxAdventures/modelexhibit.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/shapes.ts, src/StarFoxAdventures/skeleton.ts, src/StarFoxAdventures/textures.ts, src/StarFoxAdventures/util.ts, src/StarFoxAdventures/world.ts
Avoid allocating matrices and colors, simplify calculations
=> SFA: More optimizations

src/BanjoKazooie/render.ts, src/Common/N64/RDP.ts
Also left in some helper methods I wrote for color combiner debugging
(If there's a better spot to put those helper methods I can move them ofc, just wasn't sure where the best place for them was)
=> Fix some inaccuracies in N64 color combiner implementation

src/StarFoxAdventures/animation.ts, src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/materials.ts, src/StarFoxAdventures/modelexhibit.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/shapes.ts, src/StarFoxAdventures/util.ts, src/StarFoxAdventures/world.ts
Reduces the number of renderpasses. Also reduces the number of times iterating over each object. Performance improves from 20fps to 27fps on my system.
=> SFA: Performance improvements

src/ui.ts
A mistake in #345, sorry about that!
Didn't notice it was wrong.
=> ui: Fix default FOV slider position

src/BeetleAdventureRacing/ParsedFiles/UVMD.ts, src/BeetleAdventureRacing/ParsedFiles/UVTX.ts
Realized I forgot to open a PR for this after I committed it - just fixes the texture offsets being slightly wrong.
=> BAR: Fix texture matrix calculation

src/SourceEngine/Scenes_HalfLife2DM.ts, src/main.ts
Creating HL2:DM scenes based on HL2/SourceEngine code
=> Adding support for HL2:DM

src/SourceEngine/Scenes_CounterStrikeSource.ts, src/main.ts
Three maps crash as of this writing and have been commented out, needs more research but this works as a v1
=> Adding rudimentary CS:S support

src/SourceEngine/Scenes_TeamFortress2.ts
Updates the scene list for Team Fortress 2 with all current working maps (crashes or noteworthy bugs are commented about)
=> TF2: Full map list

src/SourceEngine/Scenes_Portal2.ts
This level is actually from the Super 8 "bonus" teaser found in the Extras menu of Portal 2
=> Adds category name for unknown Portal 2 level

src/StarFoxAdventures/blocks.ts, src/StarFoxAdventures/fur.ts, src/StarFoxAdventures/maps.ts, src/StarFoxAdventures/materialloader.ts, src/StarFoxAdventures/materials.ts, src/StarFoxAdventures/modelloader.ts, src/StarFoxAdventures/models.ts, src/StarFoxAdventures/objects.ts, src/StarFoxAdventures/render.ts, src/StarFoxAdventures/resource.ts, src/StarFoxAdventures/shapes.ts, src/StarFoxAdventures/textures.ts, src/StarFoxAdventures/world.ts
Also fixes potential issues when multiple instances of a map block are present.
=> SFA: Destroy resources when exiting a map

src/MathHelpers.ts, src/gfx/helpers/BufferHelpers.ts, src/gx/gx_displaylist.ts, src/gx/gx_enum.ts, src/gx/gx_material.ts, src/metroid_prime/ancs.ts, src/metroid_prime/anim.ts, src/metroid_prime/animation/base_reader.ts, src/metroid_prime/animation/char_anim_time.ts, src/metroid_prime/animation/data_source.ts, src/metroid_prime/animation/meta_nodes.ts, src/metroid_prime/animation/pose_builder.ts, src/metroid_prime/animation/source_readers.ts, src/metroid_prime/animation/tree_nodes.ts, src/metroid_prime/cinf.ts, src/metroid_prime/cmdl.ts, src/metroid_prime/cskr.ts, src/metroid_prime/dkcr_scenes.ts, src/metroid_prime/evnt.ts, src/metroid_prime/mrea.ts, src/metroid_prime/render.ts, src/metroid_prime/resource.ts, src/metroid_prime/scenes.ts, src/metroid_prime/script.ts, src/metroid_prime/stream.ts, src/metroid_prime/strg.ts, src/metroid_prime/txtr.ts, src/ui.ts
* Loaders for animation-related resources
* Meta animation and transition node implementations
* CPU skinning for MP1
* Loads existing envelope matrix sets for MP2
* "Show All Actors" and "Suit Model" render hacks exposed to user
=> Default actor animations for Metroid Prime 1 and 2

src/Glover/actor.ts, src/Glover/bullets.ts, src/Glover/render.ts, src/Glover/scenes.ts, src/Glover/sprite.ts
Fixing typescript errors that were laying in wait and somehow not caught by my `pnpm start` workflow (caught using `pnpm build`)
=> glover: Fix typescript errors

src/DataFetcher.ts, src/DefaultSaveStates.json, src/NeedForSpeedMostWanted/datanode.ts, src/NeedForSpeedMostWanted/map.ts, src/NeedForSpeedMostWanted/region.ts, src/NeedForSpeedMostWanted/render.ts, src/NeedForSpeedMostWanted/scenes.ts, src/main.ts
Alright, finally got around to finishing my stuff :) This adds NFS Most Wanted to the site. I've put it in Experimental because I wasn't quite sure where it would fit in, feel free to move it around.
There aren't really any changes to shared code, except for a small bug fix in DataFetcher.ts where the Range header was set incorrectly (and adding the scene group and default save state of course).
Also, I guess you'd need the data files from me? Not sure where/how I would do that.
=> Add Need for Speed Most Wanted

src/oot3d/cmb.ts, src/oot3d/csab.ts, src/oot3d/oot3d_scenes.ts, src/oot3d/render.ts, src/oot3d/zsi.ts
- Hacky support for vertex lighting until I have more time.
- Hacky/hard-coded fog support until I figure out how it's done.
- Fixed animation bug (majoras mask)
- cmb: General correction
=> oot3d: Implement vertex lighting/hacky fog for OoT/MM3D

src/TwilightPrincess/LegacyActor.ts, src/TwilightPrincess/d_a.ts, src/TwilightPrincess/d_kankyo.ts, src/TwilightPrincess/framework.ts, src/TwilightPrincess/m_do_ext.ts
also fix some of the legacy actor light types
=> Twilight Princess: kytag07 and better poe implementation

src/DragonQuest8/bundle.ts, src/DragonQuest8/chr.ts, src/DragonQuest8/img.ts, src/DragonQuest8/map.ts, src/DragonQuest8/mds.ts, src/DragonQuest8/mot.ts, src/DragonQuest8/render.ts, src/DragonQuest8/sceneInfo.ts, src/DragonQuest8/scenes.ts, src/DragonQuest8/stb.ts, src/main.ts
This pull request adds support for the PS2 version of Dragon Quest 8. Aside from the TIM2 texture specs, all the reverse engineering work has been done from scratch, on the EU version of the game. 
It also features the day night cycle and a script interpreter to have accurate NPC routines (with skeletal, visibility and facial animations also added). Options to change the current game progress and hour to check the different layouts are also implemented.
=> Dragon Quest VIII: Journey of the Cursed King (PS2)

src/HeavyIron/HIBase.ts, src/HeavyIron/HIDispatcher.ts, src/HeavyIron/HIEnt.ts, src/HeavyIron/HIEntButton.ts, src/HeavyIron/HIEntDestructObj.ts, src/HeavyIron/HIEntPickup.ts, src/HeavyIron/HIEntPlayer.ts, src/HeavyIron/HIEntSimpleObj.ts, src/HeavyIron/HIEnv.ts, src/HeavyIron/HIFog.ts, src/HeavyIron/HILightKit.ts, src/HeavyIron/HIModel.ts, src/HeavyIron/HIModelBucket.ts, src/HeavyIron/HINPCCommon.ts, src/HeavyIron/HIPlatform.ts, src/HeavyIron/HIScene.ts, src/HeavyIron/HISkyDome.ts
Made some rendering and scene loading code more accurate to the game. Fixes skydomes disappearing at certain camera heights and models not fading out at the correct distances.
=> Battle for Bikini Bottom: various fixes

src/ZeldaSkywardSword/Main.ts
Somewhere between starting this and the merge, I needed to have it be frame - 1, must've been fixed. (also properly fixed deku baba subtype)
Also removes extra model on top of lumpy pumpkin
=> Skyward Sword: Fix Animation Frame Mapping (Rupees/Chus)

src/MarioKart8Deluxe/Render.ts
Adds transmission support in the shaders along with some decal trail types which fixes the brightness on certain roads and surfaces.
=> Mario Kart 8 Deluxe: Add support for transmission and decal trails.

rust/src/wow/wmo.rs, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/scenes.ts
Turns out we've been rendering many many copies of the same models, including entire capital cities (!). Also adjusts the liquid colors a bit.
=> wow: deduplicate WMOs and Doodads based on UID

rust/src/wow/wmo.rs, src/WorldOfWarcraft/data.ts
Fixes incorrect liquid types and uses the "deep" color by default (it looks better IMO, eventually we should get the liquid depth data though)
=> wow: various liquid fixes

rust/src/wow/animation.rs, rust/src/wow/sheep.rs
Fixes some broken animations, simplifies the animation manager a bit
=> Wow animation fix

rust/src/wow/adt.rs, rust/src/wow/db.rs, rust/src/wow/wmo.rs, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/render.ts
* handle deep/shallow rivers and oceans, use correct liquid transparency values
* make particle volumes invisible
=> misc wow fixes

rust/src/wow/animation.rs, rust/src/wow/common.rs, rust/src/wow/m2.rs, rust/src/wow/wmo.rs, src/DefaultSaveStates.json, src/MathHelpers.ts, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/debug.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/render.ts, src/WorldOfWarcraft/scenes.ts
Adds animated M2 lights and uses ambient WMO colors correctly
=> Fix wow model lighting

rust/src/wow/db.rs, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/render.ts, src/WorldOfWarcraft/scenes.ts
We'll now correctly tween between multiple skybox models
=> wow: Handle multiple skyboxes

.vscode/launch.json, rust/src/wow/animation.rs, rust/src/wow/common.rs, rust/src/wow/m2.rs, src/DefaultSaveStates.json, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/render.ts, src/WorldOfWarcraft/scenes.ts
=> Add wow particles

rust/src/wow/adt.rs, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/render.ts, src/WorldOfWarcraft/scenes.ts
* No longer loads duplicate WMO definitions
* Major improvements to WMO vertex color picking
* Animate particle emitters at lower framerates if they're further away
=> Dedupe wmos

src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/scenes.ts
Also adds more sensible camera defaults if they're not present
=> Load fewer ADTs before rendering the scene

src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/program.ts, src/WorldOfWarcraft/render.ts
This reduces the size of our uniform buffers by a ton
=> wow: Use textures for bone data

src/ZeldaWindWaker/tools/zww_extractor.ts
Without this change, the script will fail if data/ZeldaWindWaker does not already exist
=> Update zww_extractor.ts to create the output directory if it does not already exist

src/ZeldaWindWaker/tools/zww_extractor.ts
This now assumes the disc is extracted with Dolphin layout (files/, sys/) and fixes Linux support
This needs to be done for TP as well
=> ZeldaWindWaker: Support case-sensitive FS & use Dolphin extract layout

src/byml.ts
Resolves issues introduced in 89aa596b15f39a13b2e52b2d3ba99991fc729fe4
Reproduce errors with `pnpm run build:ZeldaWindWaker`
=> byml: Fix GrowableBuffer

rust/src/geometry.rs, rust/src/wow/common.rs, rust/src/wow/db.rs, rust/src/wow/m2.rs, rust/src/wow/skin.rs, rust/src/wow/wmo.rs, src/DebugJunk.ts, src/WorldOfWarcraft/data.ts, src/WorldOfWarcraft/render.ts, src/WorldOfWarcraft/scenes.ts, src/gfx/helpers/DebugDraw.ts
This addresses a couple bugs in the existing lighting/skybox models:
* adds zone lighting
* using unsigned data types for signed values
* not sorting batches as it's done on client
* better tweening and handling of multiple lighting influences
=> Fix wow skyboxes
