magcius/noclip.website

src/Camera.ts
src/ui.ts

Adding a Camera Speed Slider to the viewer settings. I also hooked up
the slider to also update on the mouse wheel event, so that the camera
speed can still be set like it was previously, or by using this new
slider. Because of the addition of this slider, the max camera speed is
1000 normally, or 5000 if you are holding shift. Max speed could be adjusted if we want to make it higher or lower, but I felt like this was a pretty good balance.

Adding New Camera Speed Slider

---

src/kh2fm/map.ts
src/kh2fm/program.glsl
src/kh2fm/render.ts
src/kh2fm/scenes.ts
src/main.ts
src/ps2/gs.ts

Parser and renderer for Kingdom Hearts II Final Mix (PS2). Final Mix contains a few extra maps including Cavern of Remembrance, Data Battles and some extra cutscenes.
.MAP files should be placed in: `data/kh2fm/`
This also includes a common library for EE GS operations in `src/ps2/gs.ts` copied from Katamari's parser, which could be used by KH1 and Katamari at some point in the future.

Add support for Kingdom Hearts II Final Mix

---

src/kh/render.ts
src/kh2fm/map.ts
src/kh2fm/render.ts

Small fixes for Kingdom Hearts renderers:
* Kingdom Hearts II Final Mix: 
* Handle geometry flag which changes blending function via ALPHA_1.
* Update TEXA animation timer to work with rewind, and fix timer breaking after tabbing out of the window.
* Kingdom Hearts:
* Change texture filtering from point to bilinear.

Rendering fixes for KH and KH2FM

---

src/kh2fm/map.ts

Caused by some maps setting minLength = 0 and maxLength = 0 for some frames in TEXA blocks, resulting in the animation timer never advancing. Examples:
- Mysterious Tower: Star Chamber
- Halloween Town: Candy Cane Lane

kh2fm: Fix TEXA timer looping infinitely in some maps

---

src/Pilotwings64/Scenes.ts

The actually texture mapping is nowhere near correct yet.
I changed MeshInstance into MeshRenderer based on the bk naming, and it now has a collection of MaterialInstance s (not married to the name) which actually do the rendering.
I added a method to the TextureHolder that probably shouldn't be there, but it seemed preferable to unprotecting the equivalent method or adding an index->address lookup table, since everything uses those indices instead of addresses. 
I could also leave out the dummy texture, I just thought it would be visually helpful.

Pilotwings 64: Texture things mostly correctly

---

src/Common/N64/Image.ts
src/Pilotwings64/Scenes.ts
src/bk/f3dex.ts
src/bk/render.ts

- Set scrolling texture dimensions correctly
- Fix I4 and IA4 decoding
- Properly handle paired textures in tile 0
- Check 2-cycle and filtering "other" modes

Pilotwings 64: Fix lots of small texture issues.

---

src/BanjoKazooie/f3dex.ts
src/BanjoKazooie/geo.ts
src/BanjoKazooie/render.ts
src/BanjoKazooie/scenes.ts
src/BanjoKazooie/tools/extractor.ts

Just add objects that are always spawned on level load for now,
as others may have a different data format. Even some of these
use a new type of file which I haven't looked into yet.
Add a persistent store for the model data, maybe more later.
Interpret model file associations (and animation metadata) from
the code. The alternative was parsing a blob with lots of different
data, which seemed error prone.
Also fix two small bugs: a render template instance memory leak
and a missing "/2" in the f3dex G_VTX code.

BanjoKazooie: Start adding objects from setup files.

---

.parcelrc
.terserrc
.vscode/launch.json
package.json
src/BuildVersion.ts
src/GrandTheftAuto3/render.ts
src/PaperMario64/render.ts
src/embed.html
src/embeds/embeds_main.ts
src/index.html
src/kh/render.ts
src/kh2fm/render.ts
src/main.ts
src/psychonauts/render.ts
src/tools/generate_screenshots.ts
src/ui.ts
tsconfig.json
webpack.common.js
webpack.dev.js
webpack.prod.js
yarn.lock

Hi, I saw off-hand in the urde discord that you were looking for help trying out Webpack. Here's what I came up with that matches the existing build process as closely as possible.
Some notes on wasm:
- I tried making the AssemblyScript compilation a part of the Webpack build, but the existing loaders for it don't work well & are seemingly not maintained.
- Webpack v4 does include [async importing *.wasm files](https://github.com/webpack/webpack/tree/v4.41.2/examples/wasm-simple), but I did not try that out yet.
Instead, just using `CopyWebpackPlugin` to copy the existing wasm files to the dist root works for now.

Convert project to Webpack 4

---

src/MathHelpers.ts
src/j3d/ztp_scenes.ts
src/rres/Scenes_MarioKartWii.ts

Keeps spawned objects in the correct place, despite not being set yet.

ztp: Improve mirror render hack

---

src/Common/Compression/LZO.ts
src/metroid_prime/dkcr_scenes.ts
src/metroid_prime/mrea.ts
src/metroid_prime/pak.ts
src/metroid_prime/resource.ts
src/metroid_prime/scenes.ts

Port jackoalan/lzokay@671e2b9 decompressor to typescript and integrate with MP2/3 loaders.
Transforming LZO to ZLIB in PAKs is no longer necessary.

Add LZO decompression for Retro games

---

src/Camera.ts
src/InputManager.ts

This PR adds basic (crude) touch controls, in order to make noclip usable on mobile devices.
The following touch controls are implemented:
The following features would be desirable, but are not implemented by this PR:

Add basic touch controls

---

src/gfx/shaderc/GfxShaderCompiler.ts

This is currently preventing most Wind Waker shaders from compiling if the environment has the `row-major` avoidance hack enabled.

Fix typo in Mul(Mat4x3, vec4)

---

src/j3d/WindWaker/DZB.ts

This is needed for tree shadows (they orient themselves based on the ground normal). I'm definitely up for doing this another way, this just seemed to be the most straightforward.

Wind Waker: Add optional normal output to DZB `raycast()`

---

src/SpongeBobBFBB/assets.ts
src/SpongeBobBFBB/program.glsl
src/SpongeBobBFBB/render.ts
src/SpongeBobBFBB/scenes.ts
src/SpongeBobBFBB/util.ts

This adds support for ENV assets, which specify which LightKit to apply to objects, among other things, as well as more render hacks:
- Fog (on/off)
- Skydome (on/off)
- Show Invisible Entities (on/off)
- Show Invisible Atomics (on/off)
A new BaseRenderer class and RenderState interface have also been added to encapsulate common properties and methods used throughout many renderer types.

BFBB: ENV support and more render hacks

---

src/BanjoKazooie/render.ts
src/Pilotwings64/Scenes.ts

Currently, the Banjo-Kazooie renderer uses dynamic array indexing to get combine parameters. With this patch, a new fragment shader is compiled for each set of combine parameters. This greatly improves performance on one of my weaker machines, and is potentially compatible with more browsers.

BJ: Compile new fragment shader per combine parameters

---

src/SuperMario64DS/nitro_tex.ts

fixed NitorTex A5I3.
I coding mph stages on noclip website.
and recognized NitroTex's A5I3 is incorrect.
https://github.com/hackyourlife/metroidprimehunters/blob/1c3170b35d8b3465a6b2df3c4c3097f3a2316d73/models/scene.c#L578
this is hackyourlife's itegrated ndsgraph(first mph model viwer).
it's support A3I5 and A5I3 by NoneGiven.

NitorTex A5I3 fixed

---

src/PaperMario64/tools/extractor.ts

At some point, `src/compression` was moved to `src/Common/compression`, but this particular map data extraction script's imports was not updated to reflect this! This one-line change resolves this issue :)

Paper Mario 64: Fix extractor.ts

---

src/Camera.ts
src/CameraAnimationManager.ts
src/ui.ts

This PR adds a few fixes to the Noclip Studio feature introduced in #325, and a couple new bits. Namely:
- Tangent calculation has been simplified, with some logic errors fixed to produce [buttery-smooth transitions](https://gfycat.com/amusingapprehensiveguineafowl).
- We no longer clamp the t value at the end of each keyframe (f1ee498), which was likely causing the occasional jutter/delay on transitions between keyframes. (This change is not reflected in the animation linked above.)
- Edit Position mode can now be cancelled with Escape. Help text has been updated to reflect this.
- State tracking for the UI is moved to the UI class to the greatest extent possible.
- CameraAnimationManager no longer tracks the selected keyframe index, instead retrieving it from a data attribute on the …

Noclip Studio - Fixes and Enhancements

---

src/Camera.ts
src/CameraAnimationManager.ts
src/ui.ts

This PR introduces some more data management options and quality-of-life features to Studio Mode.
- Whenever a new scene is loaded with studio mode active, the animation for that scene is loaded from local storage, if one exists. Also fixes a bug where the studio camera controller is deselected when switching scenes.
- Added a "New" button which clears the current animation.
- Animations are auto-saved on every non-destructive edit (basically, everything except deleting keyframes and clicking "New"). This is perhaps a bit overzealous. I'm open to only auto-saving on scene changes instead.
- Keyframe names are now saved and loaded with animations.
- Added buttons for "Export" and "Import", which save and load animations as JSON files. Some very basic validation and error handling is also …

Studio - Data Management Improvements

---

src/Camera.ts
src/CameraAnimationManager.ts
src/ui.ts

This PR introduces some improvements to the interpolation methods used in Studio mode.
- A bug in the playback engine has been fixed. Now, if the delta time between one animation step and the next overruns the current keyframe's duration, we save that value and carry it over to the next keyframe. I've done some testing and haven't noticed any issues with this yet, and it should help to reduce judder on keyframe boundaries.
- Interpolation is now done via the generation of a lookAt matrix (or targetTo matrix, more precisely) every animation step, so that we can use Hermite interpolation on both rotation and translation. The difference between [quaternion slerp](https://gfycat.com/neighboringultimateblacknorwegianelkhound) and [Hermite](https://gfycat.com/charmingaromaticivorybackedwoodswall …

Studio - Interpolation Improvements

---

README.md
src/Camera.ts

In most engines, the default behaviour for noclip cameras is to slow the camera to from the set speed when the control key is pressed. Most of the time, the value is reduced to 1/10th. This is usually used to finely control the camera into small areas. This kind of tripped me up at first when I came across the site - because I was used to this hotkey working. So, I've added it using the same logic as the shift hotkey.
I've made this hotkey takes priority over the shift key, but I can easily change it if you think it should be the other way around.
If I use ```cl_showpos 1``` to show the velocity of the camera, you can see that the default speed is 500 Hu/S:
But if I press shift while noclipping, the speed triples
And when pressing control it is divided by ten
Because of interference by …

Fine control camera hotkey

---

src/ui.ts
src/viewer.ts

Low FoV values such as 45 are common in console games where the TV
screen is usually quite far, but not so in Desktop/mobile scenarioes
where noclip.website is most commonly used for.
Values of 80-90 are much more common in these cases, I picked 60 since
it's around the middle (also it divided evenly).
---
The exact value is of course open to bikeshedding (should probably be even more?), but I do believe it's necessary to increase it.

viewer: Increase default FoV from 45 to 60 degrees

---

src/BanjoKazooie/render.ts

First alpha value was set to `combAlpha` for all alpha parameters, but for the multiply parameter it's supposed to be LOD_FRACTION (See [here](https://github.com/gonetz/GLideN64/blob/master/src/Combiner.cpp#L63)). Noticed because it was causing some textures in BAR to have the incorrect transparency.

Fix incorrect alpha parameter in F3DEX_Program

---

src/Common/JSYSTEM/J3D/J3DGraphAnimator.ts
src/Common/JSYSTEM/J3D/J3DGraphSimple.ts
src/Common/JSYSTEM/J3D/J3DLoader.ts
src/SuperMarioGalaxy/Animation.ts
src/WindWaker/m_do_ext.ts
src/j3d/mkdd_scenes.ts

First time writing in TypeScript... I have changed some stuff for MKDD.
* Added support for BCA animations (probably bad implementation).
* Implemented BOL rotation correctly (very wrong before, even though it worked most of the times). I also added reading for object settings.
* Changed how files are loaded from the RARC course. It uses a more similar way of reading data which the original game does. It also reads all supported animations of both course BMD and skybox BMD.
* Changed how objects are loaded. They now must specify both the BMD name and what animations to load.
* Added a lot more objects. The object loading is simplified, only the BMD and in some cases, animation files, are loaded. Nothing else has been done (no moving etc). The file names are hardcoded in a giant switch …

Improved MKDD. Objects, BCA, rotation fix and more

---

src/Camera.ts
src/ui.ts

Just a couple quick fixes for some UI stuff in the Studio panel.
- Fixed some button styling. I was borrowing some styling from other UI buttons, a class that was lost somewhere in the mix. Now the buttons are styled on their own.
- Changed the delete keyframe button from an emoji to a Unicode multiplication sign. Should hopefully fix the missing glyph character that was appearing for some folks.
- Refactored `StudioCameraController` to stop creating savestates during animation playback.

Studio UI Fixes

---

src/gx/gx_texture.ts

Fixes issue in MP2 where a 32x64 I8 texture has a 4x8 mip level and only one padded block instead of two.

Discard mip levels that do not have enough data available.

---

src/BeetleAdventureRacing/TrackData.ts

Tested on local copy, planes display and I don't see any errors in the console

Fix plane renderer index array size

---

src/j3d/sms_scenes.ts

The game first organizes light sources into four `TLightWithDBSet`s:
0: `TPlayerLightWithDBSet`
1: `TObjectLightWithDBSet`
2: `TMapObjectLightWithDBSet`
3: `TIndirectLightWithDBSet`
Each of these search by name into the `LightAry` and `AmbAry` loaded from the scene.bin. However, `TObject…`, `TMapObject…`, and `TIndirect…` all search for the same name, so they are collapsed for this implementation. Additionally, the index into the `LightAry`/`AmbAry` is adjusted when an object is in shadow, but that is not yet
implemented here.
Also some scene names from stagename.bmg and scenarioname.bmg.

Super Mario Sunshine: Initial implementation for object lighting

---

src/JetSetRadio/Ninja.ts
src/JetSetRadio/Scenes.ts
src/JetSetRadio/tools/extractor.ts

Changes the binextractor's API a bit to be more 'comfortable' with the variable data structures between stages.
Also adds STAGE2.AFS and STAGE3.AFS
Stage 2+3 has some positioning problems, but they are recognizable. 
Fixes a bug where NJS_OBJECTS would assume that it has a model and try to load it from an invalid address

JetSetRadio: Extractor Changes + Additional stages

---

src/SourceEngine/BSPFile.ts
src/SourceEngine/EntitySystem.ts
src/SourceEngine/Materials.ts
src/SourceEngine/Scenes.ts
src/SourceEngine/Scenes_Infra.ts
src/SourceEngine/Scenes_Portal.ts
src/SourceEngine/Scenes_Portal2.ts
src/SourceEngine/StaticDetailObject.ts
src/main.ts

* Infra scene groups
* Branches in BSP loader for version 22
* HDR sky materials (only method A right now)
* All remaining `CalcDetail` combine modes present in 2013

Source Engine: Changes to support Infra maps

---

src/Studio.ts

This PR introduces an enhancement and fixes a few more issues with Studio Mode:
- Bank rotation now uses absolute values, inferred by adding the smallest-magnitude value to the previous rotation to achieve the rotation of the keyframe at the time of its creation. Loops are handled by modulo-ing out any full rotations between the last keyframe and the loop keyframe. Thanks to @PFedak for cleaning up my spaghetti here.
- The bank rotation value display now shows an arc tracing the path between the previous bank rotation value and the current one. Doesn't work properly for value changes greater than 360 degrees in magnitude, but that would typically only happen if 
- Removed the logic forcing all Start/Loop End keyframes to be selected simultaneously, allowing different interpolation …

Studio: Bank Rotation Improvement, Cleanup, and Bug Fixes

---

src/metroid_prime/render.ts
src/metroid_prime/scenes.ts
src/metroid_prime/script.ts
src/metroid_prime/ui.ts
src/ui.ts

Adds `UI.GroupLayerPanel` which functions like `UI.LayerPanel` by default, but in the presence of two or more unique `layerGroup` fields, displays layer group tabs.
It has been applied to MP2's light/dark maps like so:

UI: Extended layer panel for grouping light/dark MP2 maps

---

package.json
pnpm-lock.yaml

1fd8c2798f8467d44db3555655b1f7a092db6de1 pinned this to 0.10.1 because 0.10.2 had issues, but now 0.10.3 is released we don't need to do that anymore.
Fixes build on arm64 (e.g. M1/M2 Macs).

Bump wasm-pack to ^0.10.3

---

src/ui.ts

Various things can cause dragging to end without us registering a mouseup event, such as another window popping up, an exception or breakpoint, or leaving the window area. While this might be the right use case for ondragleave etc. I couldn't get that to work.
This just does the obvious thing and stops dragging if the mouse buttons are up, which handles the annoying cases like the Portal 2 workshop window without impacting normal dragging too much.

Cancel dragging over ScrollSelects if mouse buttons are up.

---

src/Common/Compression/Yaz0.ts
src/Common/JSYSTEM/JKRArchive.ts
src/Common/Unity/AssetManager.ts
src/Halo1/scenes.ts
src/Halo1/tex.ts
src/Scenes_FileDrops.ts
src/fres_nx/tegra_texture.ts
src/gfx/platform/GfxPlatformWebGPU.ts
src/gx/gx_texture.ts
src/main.ts
src/rustlib.ts

Centralises the loading and referencing of the Rust WASM lib. Atm its being loaded in specific places and requires that wherever you do load it is set up to be async. This moves loading to the main method (which is already async) and can be referenced now from all code. 
It simplifies some workarounds that were currently in the code. I'm not that familiar with web tech so I'm not sure if there's a performance hit of loading in main vs only when necessary.. but it seems like it was used in some hot paths likely to be hit anyway.

Enhancement: Centralize Loading/Usage of Rust WASM

---

src/DebugJunk.ts

Fixes https://github.com/magcius/noclip.website/issues/448#issuecomment-1621592596
The studio camera path visualization was drawing over UI elements due to it being appended after the main drawing canvas.

Fix studio camera path visualization

---

src/rres/brres.ts

For some reason, when dropping custom files (such as Mario Kart Wii custom tracks) on the website, the page could freeze. It appear that the value "lastFrame" in "getAnimFrame" would be equal to 0, and if the loop mode is on repeat, the website would end up on an infinite loop.
Tested with this custom track : 
https://drive.google.com/file/d/1kttPIdbj6LF-Qdz9tFAbVC3k2YR9Lesv/view?usp=sharing

getAnimFrame could get stuck in an infinite loop

---

src/TwilightPrincess/d_a.ts
src/TwilightPrincess/d_kankyo.ts
src/TwilightPrincess/d_stage.ts
src/TwilightPrincess/framework.ts
src/TwilightPrincess/ztp_scenes.ts

This changes the layer tab to a single select to have each layer be it's own scenario. For example this lets you switch to layer 14 on maps that have twilight to view the twilight version of the map, reinitializing the lighting appropriately. This also fixes bg_obj actors to be tied to the correct layer as their parent set_bg_obj actor

Twilight Princess: Implement layer scenario switching

---

src/TwilightPrincess/d_kankyo.ts
src/TwilightPrincess/d_kankyo_wether.ts
src/TwilightPrincess/d_stage.ts

the base of housi is mostly unchanged from tww. just a few number changes and adding a rotation. the original game uses it to handle both twilight effects and some particles in fishing pond, but this is only twilight effects for now. kumoCol alpha fix to fix skybox colors

Twilight Princess: basic housi implementation / fix kumoCol

---

src/SpongeBobBFBB/render.ts

This fixes a bug where all skydome entities were going into the main pass instead of the sky pass, causing them to draw over other objects in the scene. This was because EntRenderer would set the render inst list to the sky one but then it would get reset back to the main one when EntRenderer called prepareToRender on each of its models. The solution is to not reset the render inst list in BaseRenderer, but instead reset it once at the beginning of the scene and once after rendering each entity.

BFBB: Fix sky rendering bug

---

src/nns_g3d/NNS_G3D.ts

This commit changes how joint matrices are constructed for NSBMD nodes with pivotIdx values of 1 and 2. (Rotation data was being written outside of the 3x3 rotation matrix for both nodes, and the rotation encoded for a pivotIdx of 2 appeared incorrect.)
Not many scenes live on the site use these nodes, but a few look better after this: [a bowser statue flips upright](https://noclip.website/#mkds/old_koopa_agb;ShareData=AT-9*92S&Q8|f+B9R6n^=/vfZ6W!oFUfyRn9RXJT=u=CBURjbL9a-&{9i\)Z~=2), [a building's shadows in Pokemon Platinum](https://noclip.website/#pkmnpl/0;ShareData=AO2S~UmPkuT!d,89o=?1X21RyP^}AZUt{,[T12svW~F^WUg!9e8{v]NUp\(pkXL) no longer extend to the heavens, and [one room in Pokemon HGSS](https://noclip.website/#pkmnsslvr/301;ShareData=AX:-JUV_DRS,RfB7(*Vh=uuM=P,GM}UmSe)Ui8aqW+PSWTLF …

NNS_G3D: Fix some node rotation matrices

---

src/Glover/sprite.ts

at some point the sprites for glover weather rendering ended up behind the 3D scene instead of in front of it. i screwed with with the sort keys for a bit, but ultimately what fixed the regression was bringing the sprites to z coordinate -1. not entirely sure what changed or why this fixes it, but life's short and i've got Ripley to watch

glover: fix weather sprite depth sorting

---

rust/src/wow/wmo.rs
src/DefaultSaveStates.json
src/WorldOfWarcraft/data.ts
src/WorldOfWarcraft/program.ts
src/WorldOfWarcraft/render.ts
src/WorldOfWarcraft/scenes.ts

The waterwheel in Warsong Gulch is currently all-black due to the weird case of WMO groups which share the same doodad. I couldn't find any docs on how this is handled, and didn't really see where WowWebViewer handles it, so simply choose the group that's closest to the doodad as its group for the purposes of lighting.

wow: Fix WMOs with shared doodads

---

rust/src/geometry.rs
rust/src/util.rs
rust/src/wow/wmo.rs
src/SourceEngine/BSPFile.ts
src/WorldOfWarcraft/data.ts
src/WorldOfWarcraft/debug.ts
src/WorldOfWarcraft/scenes.ts

When we clip a frustum through a WMO group's portal, use that clipped
frustum to cull things outside. Also, perform the group membership check
in rust, which is both more convenient and faster.
Fixes a couple bugs also

wow: use clipped frustums to cull exterior

---

src/SourceEngine/Scenes_EstrangedActI.ts
src/SourceEngine/VMT.ts
src/main.ts

Hi, I'm the project lead for the Source Engine mod [Estranged: Act I](https://store.steampowered.com/app/261820), and if you'll accept it, I'd like to add its levels to the archive. Here's a partially working first level using the content from Steam.
Beyond the changes in this PR already, the renderer appears to choke in a number of places, and a number of levels are broken. In addition, lightmaps do not work across all levels. I'd appreciate some help with breaking these issues down.

Estranged: Act I

---

src/Common/JSYSTEM/J2D.ts
src/Common/JSYSTEM/J2Dv1.ts
src/ZeldaWindWaker/Main.ts
src/ZeldaWindWaker/d_demo.ts
src/ZeldaWindWaker/d_place_name.ts
src/ZeldaWindWaker/d_procname.ts
src/ZeldaWindWaker/d_resorce.ts
src/ZeldaWindWaker/framework.ts

- Added `src/Common/JSYSTEM/J2D.ts`
- Added new automatic file type handling, `BLO` (Binary Layout). 
- Added `fopMsgM` functionality to `framework.ts`
- Implemented place names handing in `src/ZeldaWindWaker/d_place_name.ts`
BLO files contain layout data for 2D elements. It is made up of a hierarchy of J2DPanes (essentially just a bounding box) and J2Pictures. Child elements inherit the transform from their parents. The entire hierarchy contained in a single root J2DScreen object. I followed the pattern of J3D and split up the loading functions from the runtime objects. 
J2D and BLO files can also be used to render message boxes during demos. I'm hoping that others will find uses for them as well. 
As for place names: currently, the only ones that will display are Outset Island and The …

J2D: Implement JSystem 2D rendering library, use it display Wind Waker place names 

---

src/Common/JSYSTEM/J2Dv1.ts
src/Common/JSYSTEM/JPA.ts
src/ZeldaWindWaker/Main.ts
src/ZeldaWindWaker/d_a.ts
src/ZeldaWindWaker/d_drawlist.ts
src/ZeldaWindWaker/d_particle.ts

- Added Simple particle system (shares emitters for common particle types, eg. flame) 
- Removed a few TODOs and HACKs related to this (more to come)
- Allow particles for which `(userID & 0x4000)` is true to be drawn in a particle group other than `Projection`/`Indirect`
- Introduced ParticleGroup enum. Partially determines partical draw order, and in the future some other state such as the current view matrix
- Add support for 2D/UI particle groups
- These emitters expect different view/proj matrices (ortho, 640x480), and to be drawn later than the 3D emitters
- Fixes incorrect Y position of flame emitters (d_a_ep). Simple particles ignore the emitter translation from their definition, resulting in flame emitters being 20 units lower which matches up with the original game (see flame …

Wind Waker: Particle system improvements 

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/compression.rs
rust/src/unity/asset_file.rs
rust/src/unity/types/binary.rs
rust/src/unity/types/wasm.rs
src/AShortHike/Scenes.ts
src/Common/Unity/AssetManager.ts
src/Common/Unity/GameObject.ts
src/OuterWilds/Scenes.ts
src/main.ts

sorry for the weird branch name, i'm trying out `jj` which doesn't _do_ branches.

Unity fixes + decrunching

---

rust/src/unity/types/binary.rs
src/Common/Unity/AssetManager.ts

Instead of doing `u8::read()` in a hot loop, just pull out the entire array of bytes at once.

Unity optimization + bugfix

---

.env
src/DataFetcher.ts
src/env.d.ts

Allows overriding the storage URL using a build-time env var
The `PUBLIC_` prefix is a convention that allows the code to pull it in: https://rsbuild.dev/guide/advanced/env-vars#public-variables

Use PUBLIC_STORAGE_URL variable

---

rust/Cargo.toml
rust/src/wow/common.rs
src/WorldOfWarcraft/data.ts

One of the last very broken elements of WOTLK was that none of Zul'Drak loaded -- this adds a few hacky edge cases which fix it.

Fix zuldrak

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/halo/bitmap.rs
rust/src/halo/common.rs
rust/src/halo/map.rs
rust/src/halo/model.rs
rust/src/halo/scenario.rs
rust/src/halo/shader.rs
rust/src/halo/tag.rs
rust/src/halo/util.rs
rust/src/halo/wasm.rs
rust/src/unity/mod.rs
rust/src/unity/types/binary.rs
rust/src/wow/db.rs
rust/src/wow/m2.rs
src/Halo1/scenes.ts

Deku vastly simplifies the deserialization code here. We can also rip out nearly all of the `wasm.rs` interface thanks to both improved QOL in wasm-bindgen and just uhhhh me knowing how to use wasm-bindgen better these days.

Halo: convert to deku
